#!/bin/env bash

DIR=$(pwd)
SUB_CMD=$1
shift

case $SUB_CMD in
  new)
    docker run --rm -it -v"$DIR/content:/opt/mdtool/site/content" jayven/mdtool hugo new $@
    ;;
  serve)
    docker run --rm -it -v"$DIR:/opt/mdtool/site/themes/site-content" --network=host jayven/mdtool hugo serve $@
    ;;
  pub)
    docker run --rm -it -v"$DIR:/opt/mdtool/site/themes/site-content" jayven/mdtool hugo $@
    ;;
  *)
    echo "Invalid sub command. Valid sub commands are:"
    echo "  'mdtool new':      run 'hugo new' under current working dir"
    echo "  'mdtool serve':    run 'hugo serve' under current working dir"
    echo "  'mdtool pub':      run 'hugo' under current working dir"
    exit 1
    ;;
esac
