#!/bin/env bash

USER=$(id -u)
GROUP=$(id -g)
DIR=$(pwd)
SUB_CMD=$1
shift

mkdir -p $DIR/config $DIR/content $DIR/resources $DIR/public
touch $DIR/.hugo_build.lock

COMMON_ARGS="--rm -it --network=host --user $USER:$GROUP \
  -v /etc/passwd:/etc/passwd:ro \
  -v $DIR/.hugo_build.lock:/opt/mdtool/site/.hugo_build.lock \
  -v $DIR/config:/opt/mdtool/site/config:ro \
  -v $DIR/content:/opt/mdtool/site/content \
  -v $DIR/resources:/opt/mdtool/site/resources \
  -v $DIR/public:/opt/mdtool/site/public"

case $SUB_CMD in
  new)
    docker run $COMMON_ARGS jayven/mdtool hugo new $@
    ;;
  serve)
    docker run $COMMON_ARGS jayven/mdtool hugo serve $@
    ;;
  pub)
    docker run $COMMON_ARGS jayven/mdtool hugo $@
    ;;
  *)
    echo "Invalid sub command. Valid sub commands are:"
    echo "  'mdtool new':      run 'hugo new' under current working dir"
    echo "  'mdtool serve':    run 'hugo serve' under current working dir"
    echo "  'mdtool pub':      run 'hugo' under current working dir"
    exit 1
    ;;
esac
