#!/usr/bin/env node

var hljs = require('highlight.js')

// enable everything
var md = require('markdown-it')({
  html: true,
  linkify: true,
  typographer: true,
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(str, { language: lang }).value;
      } catch (__) {}
    }

    return ''; // use external default escaping
  }
}).use(
  require('markdown-it-sub')
).use(
  require('markdown-it-sup')
).use(
  require('markdown-it-ins')
).use(
  require('markdown-it-mark')
).use(
  require('markdown-it-emoji')
).use(
  require('markdown-it-footnote')
).use(
  require('markdown-it-deflist')
).use(
  require('markdown-it-abbr')
).use(
  require('markdown-it-dollarmath')
);

require('get-stream')(process.stdin).then((input) => {
  console.log(md.render(input))
})
