#!/usr/bin/env python3

import markdown

# https://python-markdown.github.io/extensions/
markdown.markdownFromFile(extensions=[
    'extra',
    'admonition',
    'codehilite',
    'meta',
    'nl2br',
    'sane_lists',
    'smarty',
    'toc',
    'wikilinks',
])
